// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1mOogZ93EIADZlREM72zMcxVooWdjESE',
    appId: '1:347771825200:web:498d68f97300e10f7f91f5',
    messagingSenderId: '347771825200',
    projectId: 'collectory-98647',
    authDomain: 'collectory-98647.firebaseapp.com',
    storageBucket: 'collectory-98647.firebasestorage.app',
    measurementId: 'G-KEDH5YWG6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZQedJpjPYtJ5hJMS3t7AthV5-dvnMn7Y',
    appId: '1:347771825200:android:04347f6638135c747f91f5',
    messagingSenderId: '347771825200',
    projectId: 'collectory-98647',
    storageBucket: 'collectory-98647.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsD0ua7TqGUBtumcWN1JERCyTxnCbLKn8',
    appId: '1:347771825200:ios:8a8fcd3c34bc31d17f91f5',
    messagingSenderId: '347771825200',
    projectId: 'collectory-98647',
    storageBucket: 'collectory-98647.firebasestorage.app',
    iosBundleId: 'com.example.collectory',
  );

}